Repository sirrus233/twilight-imperium-helper, pull requests merged in 2024-08, with the labels that each got.

#4 Replace number inputs with input steppers
  frontend/src/InputStepper.tsx
  frontend/src/UnitCounter.tsx
Labels: Make pretty

#3 Fighter II checkbox
  frontend/src/BudgetModeDisplay.tsx
  frontend/src/BudgetModeInputs.tsx
  frontend/src/Calculator.tsx
  frontend/src/CalculatorModeDisplay.tsx
  frontend/src/data.ts
Labels: enhancement

#7 Set up jest
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/App.test.tsx
  frontend/tsconfig.json
Labels: enhancement

#8 IaC basic setup
  .gitignore
  infrastructure/.gitignore
  infrastructure/.npmignore
  infrastructure/README.md
  infrastructure/bin/infrastructure.ts
  infrastructure/cdk.json
  infrastructure/jest.config.js
  infrastructure/lib/infrastructure-stack.ts
  infrastructure/package-lock.json
  infrastructure/package.json
  infrastructure/test/infrastructure.test.ts
  infrastructure/tsconfig.json
Labels: enhancement

#11 Rename Calculator.tsx to ProductionHelper.tsx to match component name
  frontend/src/App.tsx
  frontend/src/ProductionHelper.tsx
Labels: chore

#12 Add filters to budget mode
  frontend/src/BudgetFilters.tsx
  frontend/src/BudgetModeDisplay.tsx
  frontend/src/BudgetModeInputs.tsx
  frontend/src/DisplayField.tsx
  frontend/src/ProductionHelper.tsx
  frontend/src/data.ts
Labels: make pretty

#13 Label sidebar menu button and add minimal styling
  frontend/src/App.tsx
Labels: make pretty

#15 Convert budget section to an over/under grid
  frontend/src/BudgetCard.tsx
  frontend/src/BudgetInput.tsx
  frontend/src/BudgetModeDisplay.tsx
  frontend/src/BudgetModeInputs.tsx
  frontend/src/DisplayField.tsx
  frontend/src/InfoIcon.tsx
  frontend/src/OverUnderNumber.tsx
  frontend/src/ProductionHelper.tsx
  frontend/src/SameSizedRowGrid.tsx
Labels: make pretty

#16 Fix rendering issue - tree recreation
  frontend/src/ProductionHelper.tsx
Labels: bug

#17 Ignore bundle in eslint config
  frontend/eslint.config.mjs
Labels: chore

#18 Improve UI of budget inputs
  frontend/src/BudgetCard.tsx
  frontend/src/BudgetInput.tsx
  frontend/src/DecoratorStepper.tsx
  frontend/src/Icons.tsx
  frontend/src/InputStepper.tsx
Labels: make pretty

#20 Relabel "Total Capacity" to "Total Units" in Calculator mode
  frontend/src/CalculatorModeDisplay.tsx
Labels: make pretty

#21 Add padding around edges of app
  frontend/src/App.tsx
  frontend/src/BudgetFilters.tsx
Labels: make pretty

#22 Even out spacing between unit counter lines
  frontend/src/UnitCounter.tsx
Labels: make pretty

#19 Rename state to align with outward labels
  frontend/src/BudgetCard.tsx
  frontend/src/data.ts
Labels: chore

#23 Redirect from www subdomain
  infrastructure/bin/infrastructure.ts
  infrastructure/eslint.config.mjs
  infrastructure/lambda/redirect/index.mjs
  infrastructure/lib/infrastructure-stack.ts
  infrastructure/package-lock.json
  infrastructure/package.json
Labels: infra

#24 Disable zoom on double tap
  frontend/src/App.tsx
Labels: UX

#25 Default to number keyboard for budget input fields
  frontend/src/BudgetInput.tsx
Labels: UX

#26 Set input font size to 16px on focus (prevents mobile auto-zoom)
  frontend/src/BudgetInput.tsx
Labels: UX

#29 Redirect http to https
  infrastructure/lib/infrastructure-stack.ts
Labels: infra

#30 Add hamburger icon
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/webpack.config.js
Labels: make pretty

#31 Trade Good icon in cost rows
  frontend/src/UnitCounter.tsx
Labels: make pretty

#32 Clear button for calculator
  frontend/src/ModeToggle.tsx
  frontend/src/ProductionHelper.tsx
Labels: enhancement

#33 Change domain name
  infrastructure/lib/infrastructure-stack.ts
Labels: infra

#34 Fix 503 errors due to lambda throttling
  frontend/webpack.config.js
  infrastructure/lib/infrastructure-stack.ts
Labels: infra

#35 Remove overflow:hidden from unit cost component
  frontend/src/UnitCounter.tsx
Labels: make pretty

#36 Increase "sm" breakpoint to 330px
  frontend/src/App.tsx
Labels: make pretty, UX
